apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "spring-petclinic.fullname" . }}-pv
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  hostPath:
    path: "/mnt/data"
