apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "spring-petclinic.fullname" . }}-pvc
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
